apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
   certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ...
   server: https://172.19.113.9:443
  name: gettingstarted
- cluster:
   certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ...
   server: https://172.19.218.42:443
  name: demo

contexts:
- context:
    cluster: gettingstarted
    user: nick
  name: nick@gettingstarted
- context:
    cluster: demo
    user: nick
  name: nick@demo
- context:
    cluster: gettingstarted
    namespace: app1
    user: nick
  name: appcontext
current-context: nick@gettingstarted

users:
- name: nick
  user:
   auth-provider:
     config:
       client-id: k8s
       id-token: eyJhbGciOiJSUzI1NiIsInR5cC...
       idp-certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS...
       idp-issuer-url: https://containerauth.int.mirantis.com/auth/realms/iam
       refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSld...
     name: oidc
