apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume   # Change the name to something meaningful to your application
spec:
  capacity:
    storage: 1Gi                 # Adjust the storage capacity based on your application's requirements
  accessModes:
  - ReadWriteOnce                 # Adjust the access mode based on your application's requirements
  hostPath:
    path: "/tmp/"             # Change the path to a directory on your host machine where you want to store data
